### ISSUE TITLE
Night Mode Changes

### ISSUE THREAD

**Issue by DHgit1** [cst495Project/AnonymousAdvice#47]
Change background view to black color.
Text should be white.
TableViews Cells should be a Dark Grey / lighter black.
Text on buttons should be white.
Background of buttons should be the same color as the tableView Cells.
Make the subject collection view colors match the night theme
Segmented control should match the night theme.
Navigation controller bar match the night theme.
Save the theme to the user default for persistence.

**Comment by GarredMurphy** [comment]
I have completed most of those things except for the persistence and the navigation bar.

I am not sure how to do the persistence
